version: "3.9"
services:
  bastion:
    image: alpine/curl # Has a shell and curl installed
    command: tail -f /dev/null # Keeps the container alive to be exec-ed into later
  orders:
    build: ./tmp/orders/
    ports:
      - "8080:8080"
    environment:
      - START_ORDERS_SERVICE=true
      - ORDERS_SERVICE_HOSTNAME=http://orders:8080/
      - INVENTORY_SERVICE_HOSTNAME=http://inventory:8081/
    # network_mode: host
  inventory:
    build: ./tmp/inventory/
    ports:
      - "8081:8081"
    environment:
      - START_INVENTORY_SERVICE=true
      - ORDERS_SERVICE_HOSTNAME=http://orders:8080/
      - INVENTORY_SERVICE_HOSTNAME=http://inventory:8081/