version: "3.9"
services:
  bastion:
    image: ubuntu # TODO - need something with curl installed
    tty: true # Keeps the container alive to be exec-ed into later
  orders:
    build: ./tmp/orders/
    ports:
      - "8080:3000"
    environment:
      - START_ORDERS_SERVICE=true
      - ORDERS_SERVICE_HOSTNAME=http://orders:3000/
      - INVENTORY_SERVICE_HOSTNAME=http://inventory:3001/
    # network_mode: host
  inventory:
    build: ./tmp/inventory/
    ports:
      - "8081:3001"
    environment:
      - START_INVENTORY_SERVICE=true
      - ORDERS_SERVICE_HOSTNAME=http://orders:3000/
      - INVENTORY_SERVICE_HOSTNAME=http://inventory:3001/