version: "3.9"
services:
  orders:
    build: ./tmp/orders/
    ports:
      - "8080:3000"
    environment:
      - START_ORDERS_SERVICE=true
      - ORDERS_SERVICE_HOSTNAME=http://orders:3000/
      - INVENTORY_SERVICE_HOSTNAME=http://inventory:3001/
    # network_mode: host
  inventory:
    build: ./tmp/inventory/
    ports:
      - "8081:3001"
    environment:
      - START_INVENTORY_SERVICE=true
      - ORDERS_SERVICE_HOSTNAME=http://orders:3000/
      - INVENTORY_SERVICE_HOSTNAME=http://inventory:3001/